<!-- When the page is loaded, a new block of HTML is added at the top of the content block to handle messages returned from the Ajax newsletter signup. -->
<!--- The HTML is identical to that used by the original method (page reload) in order to maintain consistent appearance -->
<div class="fieldset ">
    <ul class="messages">
        <li id="nl_message_container">
            <ul>
                <li id="ajax_message"></li>
            </ul>
        </li>
    </ul>
</div>